# Generated by Django 4.0.3 on 2022-03-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0002_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
