# Generated by Django 4.0.3 on 2022-03-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Debit', 'Dr'), ('Credit', 'Cr')], max_length=10)),
                ('transaction_amount', models.BigIntegerField()),
                ('initiated_date', models.DateTimeField(auto_now=True)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='MidtermApp.account')),
            ],
        ),
    ]
