# Generated by Django 4.0.3 on 2022-03-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0005_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
    ]
