# Generated by Django 4.0.3 on 2022-03-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0007_rename_ssn_customer__ssn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_number']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['initiated_date']},
        ),
    ]
