# Generated by Django 4.0.3 on 2022-03-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0008_alter_account_options_alter_transaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_ssn',
            new_name='ssn',
        ),
    ]
