# Generated by Django 4.0.3 on 2022-03-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0009_rename__ssn_customer_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiated_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10),
        ),
    ]
