# Generated by Django 4.0.3 on 2022-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0011_alter_transaction_initiated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
