# Generated by Django 4.0.3 on 2022-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0014_alter_account_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Investment', 'Investment')], default='Checking', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
