# Generated by Django 4.0.3 on 2022-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0017_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
