# Generated by Django 4.0.3 on 2022-03-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0018_account_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agree',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Decline', 'Decline')], default='Accept', max_length=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Withdraw'), ('Credit', 'Deposit')], default='Debit', max_length=10),
        ),
    ]
