# Generated by Django 4.0.3 on 2022-03-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0020_alter_account_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paper_statement',
            field=models.BooleanField(default=False),
        ),
    ]
