# Generated by Django 4.0.3 on 2022-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermApp', '0024_account_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='statement',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
